export const seedPacks = [
    {
        id: 1,
        name:`Granny's Bonnet`,
        image:'../assets/products/Aquilegia.jpeg',
        type:'Flower',
        height:'15-20 in',
        light:'partial shade',
        price: 6.99,
    },
    {
        id: 2,
        name:'Carnations',
        image:'../assets/products/carnations.jpeg',
        type:'Flower',
        height:'25-30 in',
        light:'full sun',
        price: 4.49,
    },
    {
        id: 3,
        name:'Misc Large Dahlias',
        image:'../assets/products/large dahlias.jpeg',
        type:'Mix',
        height:'3-4 ft',
        light:'full sun',
        price: 7,
    },
    {
        id: 4,
        name:'Lima Beans',
        image:'../assets/products/limabeans.jpeg',
        type:'Vegetable',
        height:'1-3 ft',
        light:'full sun',
        price: 3.99,
    },
    {
        id: 5,
        name:'Farm and Flower Mix',
        image:'../assets/products/misc farm and flower.png',
        type:'Mix',
        height:'n/a',
        light:'partial shade to full sun',
        price: 5.99,
    },
    {
        id: 6,
        name:'Tulips',
        image:'../assets/products/misc tulips.jpeg',
        type:'Flower',
        height:'12-16 in.',
        light:'partial sun',
        price: 7.59,
    },
    {
        id: 7,
        name:'Cannas',
        image:'../assets/products/new cannas.jpeg',
        type:'Flower',
        height:'3-10 ft',
        light:'full sun',
        price: 6.49,
    },
    {
        id: 8,
        name:'Pansy',
        image:'../assets/products/pansy.jpeg',
        type:'Flower',
        height:'6-12 in.',
        light:'partial sun',
        price: 4.99,
    },
    {
        id: 9,
        name:'Petunias',
        image:'../assets/products/petunias.jpeg',
        type:'Flower',
        height:'6-18 in.',
        light:'full sun',
        price: 6.99,
    },
    {
        id: 10,
        name:'Pink Dahlias',
        image:'../assets/products/pink dahlias.jpeg',
        type:'Flower',
        height:'3-4 in.',
        light:'full shade',
        price: 6.99,
    },
    {
        id: 11,
        name:'Sweet Peas',
        image:'../assets/products/SweetPeas.jpeg',
        type:'Flower',
        height:'6-8 ft.',
        light:'full sun',
        price: 3.99,
    },
    {
        id: 12,
        name:'Tomato',
        image:'../assets/products/tomato.png',
        type:'Vegetable',
        height:'3-4 in.',
        light:'full shade',
        price: 6.99,
    }
];